title: 李明鸿 # your name (or website title) here
logo: "/images/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230807182358.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  哈尔滨理工大学计算机科学与技术专业本科生
  <br><br>
   目标找一个实习在七月份
  <br><br>
 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
